server:
  address: 127.0.0.1
  port: 8183
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/contactdb
    username: root
    password: root
  application:
    name: contact-service
  
  jpa:
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultzone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}