server:
  address: 127.0.0.1
  port: 9090
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      enabled: true
      routes:
      - id: user_mngmt_service
        uri: http://localhost:8192/
        predicates: 
        - Path=/mngmt/**
      
      - id: contact_service
        uri: http://localhost:8183/
        predicates: 
        - Path=/contact/**
        
      - id: user_service
        uri: http://localhost:8188/ 
        predicates: 
        - Path=/user/**

       
eureka:
  client: 
    register-with-eureka: true
    service-url:  
      defaultzone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}